config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'users#index'
  get 'help' => 'home#help'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy'

  # Twitterでのログイン
  get 'auth/:provider/callback' => 'sessions#create'

  resources :users do
    # 検索処理アクション
    collection do
      get :search_form
      get :search_result
    end
    # フォロー表示ページ
    member do
      get :following
    end
  end
  resources :posts
  resources :relationships, only: [:create, :destroy]

  # テスト用ログインアクション
  if Rails.env.test?
    post 'test/login' => 'sessions#login'
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :relationships, foreign_key: 'follower_id',
                          dependent: :destroy
  has_many :following, through: :relationships, source: :followed

  mount_uploader :image, PictureUploader
  validates :name, presence: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 150 }
  validates :blog_url, length: { maximum: 70 }
  validates :twitter_url, length: { maximum: 70 }
  validate :image_size

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    user_name = auth[:info][:name]
    profile = auth[:info][:description] ? auth[:info][:description] : ''
    blog_url =  ''
    twitter_url = auth[:info][:urls][:Twitter]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = user_name
      user.profile = profile
      user.blog_url = blog_url
      user.twitter_url = twitter_url
    end
  end

  def follow(other_user)
    relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def image_size
    if image_url.size > 2.megabytes
      errors.add(:image_url, '画像のサイズが大きすぎます')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :destroy, :following]
  before_action :correct_user, only: [:edit, :update, :destroy, :following]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])

    post_today = @user.posts.find_by(date: Date.today)
    today_working_total = post_today ? post_today.working_total : 0
    @working_today_hour, @working_today_minute =
                    convert_today_working_total_to_hours_and_minutes(today_working_total)
  end

  def index
    # ランダム表示用のインスタンス変数
    users_have_weekly_data = User.all.reject {
      |user| user.posts.where(date: (Date.today - 7)... Date.today).blank?
    }.shuffle
    @users_weekly = Kaminari.paginate_array(users_have_weekly_data).page(params[:page]).per(25)

    # 「今日」「昨日」表示用のインスタンス変数
    @posts_today = Post.where(date: Date.today).order(working_total: :desc).page(params[:page])
    @posts_yesterday = Post.where(date: Date.yesterday).order(working_total: :desc).page(params[:page])
    @q = User.ransack(distinct: true)
  end

  def following
    @user = User.find(params[:id])
    @following = @user.following.page(params[:page])
  end

  def search_form
    @q = User.ransack(distinct: true)
  end

  def search_result
    if params[:q]
      @q = User.ransack(search_params)
      @search_user = @q.result.paginate(page: params[:page])
    else
      redirect_to users_path
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'ユーザー情報を編集しました'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:info] = 'ユーザー記録を削除しました'
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :profile, :blog_url, :twitter_url, :image)
    end

    def search_params
      params.require(:q).permit(:name_cont)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user || current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build, remote: true) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id, @user.id %>
  </div>
  <%= f.submit 'フォローする', class: 'btn btn-primary follow-btn' %>
<% end %>

app/views/users/_follow_form.html.erb
<div class='follow-form'>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/users/_following.html.erb
<%= will_paginate @following, class: 'pagination-top' %>

<table class='following'>
  <tr>
    <th>ユーザ名</th>
    <th>作業時間(昨日)</th>
    <th class='table-memo'>作業内容</th>
  </tr>

  <% @following.each do |following| %>
    <tr>
      <td>
        <%= image_tag following.image.url, size: 50 %>
        <%= link_to following.name, following %>
      </td>

      <% if (post = following.posts.find_by(date: Date.yesterday)) %>
        <td>
          <%= post.working_total / 60 %>時間
          <%= post.working_total % 60 %>分
        </td>
        <td class='table-memo'>
          <%= post.memo %>
        </td>
      <% else %>
        <td>
          0時間 0分
        </td>
        <td class='table-memo'></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= will_paginate @following %>

app/views/users/_search_user.html.erb
<%= search_form_for(@q, url: search_result_users_path) do |f| %>
  <div class='search-input-group'>
    <div class='search-label'>
      <%= f.label :name_cont, 'ユーザー検索' %>
    </div>
    <%= f.text_field :name_cont, class: 'form-control',
                                placeholder: 'ユーザー名を入力' %>
    <%= f.submit '検索', class: 'btn btn-primary btn-search' %>
  </div>

<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
                                 html: {method: :delete},
                                 remote: true) do |f| %>
  <%= f.submit 'フォロー中', class: 'btn btn-primary follow-btn' %>
<% end %>

app/views/users/_weekly_table.html.erb
<%= will_paginate @users_weekly, class: 'pagination-top' %>

<table class='users'>
  <tr>
    <th>ユーザ名</th>
    <th>作業時間</th>
  </tr>

  <% @users_weekly.each do |user| %>
    <% posts = user.posts.where(date: (Date.today - 7)...Date.today) %>
    <tr>
      <td>
        <%= image_tag user.image.url, size: 50 %>
        <%= link_to user.name, user %>
      </td>
      <% working_weekly = caluculate_working_times_sum(posts) %>
      <td>
        <%= working_weekly / 60 %>時間
        <%= working_weekly % 60 %>分
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @users_weekly %>

app/views/users/_yesterday_table.html.erb
<%= will_paginate @posts_yesterday, class: 'pagination-top' %>

<table class='users'>
  <tr>
    <th>ユーザ名</th>
    <th>作業時間</th>
    <th class='table-memo'>作業内容</th>
  </tr>

  <% @posts_yesterday.each do |post| %>
    <tr>
      <td>
        <%= image_tag post.user.image.url, size: 50 %>
        <%= link_to post.user.name, post.user %>
      </td>

      <% post.convert_working_total %>
      <td>
        <%= post.working_hours %>時間
        <%= post.working_minutes %>分
      </td>
      <td class='table-memo'>
        <%= post.memo %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @posts_yesterday %>

app/views/users/edit.html.erb
<% provide(:title, "編集 | #{current_user.name}") %>

<div class='page-title'>
  <h1>プロフィールの編集</h1>
</div>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_message', object: f.object %>

      <%= f.label :name, 'ユーザー名' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :profile, 'プロフィール（最大150文字）' %>
      <%= f.text_field :profile, class: 'form-control' %>

      <%= f.label :blog_url, 'ブログ（サイト）URL  ※任意' %>
      <%= f.text_field :blog_url, class: 'form-control' %>

      <%= f.label :twitter_url, ' ツイッターURL  ※任意' %>
      <%= f.text_field :twitter_url, class: 'form-control' %>

      <%= f.label :image, 'プロフィールアイコン  ※任意' %>
      <%= f.file_field :image, accept: 'image/jpeg,image/png' %>

      <%= f.submit '変更', class: 'btn btn-primary' %>
    <% end %>

    <% if current_user == @user || current_user.admin? %>
      <%= link_to 'ユーザーの削除', @user, method: :delete,
                          data: { confirm: '本当にユーザー記録を削除してよろしいですか？'} %>
    <% end %>
  </div>
</div>

app/views/users/following.html.erb
<% provide(:title, 'フォロー一覧') %>

<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <div class='page-title'>
      <h1>フォロー一覧</h1>
    </div>
    <div id='following-table'>
      <%= render 'following' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>

<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <div class='page-title top-page-title' id='time-table'>
      <h1>
        <%= Date.today.strftime('%m月%d日') %>
        <%=  '(' + %w(日 月 火 水 木 金 土)[Date.today.wday] + ')' %>
      </h1>
      <h2>みんなの作業時間</h2>
    </div>

    <div class='search-form'>
      <%= render 'search_user' %>
    </div>
    <div class='clear'></div>
  </div>
</div>

<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <div class='btn-field'>
      <div class='change-btn today-btn active'>今日</div>
      <div class='change-btn yesterday-btn'>昨日</div>
      <div class='change-btn weekly-btn'>1週間(ランダム順)</div>
    </div>

    <div id='today-table'>
      <%= render 'today_table' %>
    </div>

    <div id='yesterday-table'>
      <%= render 'yesterday_table' %>
    </div>

    <div id='weekly-table'>
      <%= render 'weekly_table' %>
    </div>

    <p id='post-btn'><%= link_to new_post_path do %>
      <i class="fas fa-edit"></i>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<% provide(:title, 'ユーザー検索') %>

<div class='page-title'>
  <h1>ユーザー検索結果</h1>
</div>

<div class='search-form'>
    <%= render 'search_user' %>
  </div>
  <div class='clear'></div>

<%= will_paginate @search_user, class: 'pagination-top' %>

<table class='users'>
  <tr>
    <th>ユーザ名</th>
    <th>作業時間</th>
    <th>作業内容</th>
  </tr>

  <% @search_user.each do |user| %>
    <tr>
      <td>
        <%= image_tag user.image.url, size: 50 %>
        <%= link_to user.name, user %>
      </td>

      <% if (post = user.posts.find_by(date: Date.today)) %>
        <% post.convert_working_total %>
        <td>
          <%= post.working_hours %>時間
          <%= post.working_minutes %>分
        </td>
        <td>
          <%= post.memo %>
        </td>
      <% else %>
        <td>0時間 0分</td>
        <td></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= will_paginate @search_user %>

app/views/users/search_form.html.erb
<% provide(:title, 'ユーザー検索') %>

<div class='row'>
  <div class='col-xs-12'>
    <div class='page-title'>
      <h1>ユーザー検索</h1>
    </div>
    <%= render 'search_user' %>
  </div>
</div>

app/views/users/search_result.html.erb
<% provide(:title, 'ユーザー検索') %>

<div class='page-title'>
  <h1>ユーザー検索結果</h1>
</div>

<div class='search-form'>
    <%= render 'search_user' %>
  </div>
  <div class='clear'></div>

<%= will_paginate @search_user, class: 'pagination-top' %>

<table class='users'>
  <tr>
    <th>ユーザ名</th>
    <th>作業時間</th>
    <th>作業内容</th>
  </tr>

  <% @search_user.each do |user| %>
    <tr>
      <td>
        <%= image_tag user.image.url, size: 50 %>
        <%= link_to user.name, user %>
      </td>

      <% if (post = user.posts.find_by(date: Date.today)) %>
        <% post.convert_working_total %>
        <td>
          <%= post.working_hours %>時間
          <%= post.working_minutes %>分
        </td>
        <td>
          <%= post.memo %>
        </td>
      <% else %>
        <td>0時間 0分</td>
        <td></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= will_paginate @search_user %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% working_hours_total = caluculate_working_times_sum(@posts) / 60 %>
<% working_minutes_total = caluculate_working_times_sum(@posts) % 60 %>

<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
    <div class='user-profile'>
      <%= image_tag @user.image.url, size: 100 %>
      <h4>
        <%= @user.name %>
        <% if logged_in? && current_user == @user %>
          <small><%= link_to '(プロフィールを編集)', edit_user_path(@user) %></small>
        <% elsif logged_in? %>
          <%= render 'follow_form' %>
        <% end %>
      </h4>
    </div>
    <div class='total-working_times'>
      <h3>合計作業時間</h3>
      <%= working_hours_total %>時間
      <%= working_minutes_total %>分
    </div>
    <div class='clear'></div>

    <div class='user-description'>
      <p><%= @user.profile %></p>
      <p>ブログ: <%= link_to @user.blog_url, @user.blog_url, :target=>["_blank"] %></p>
      <p>Twitter: <%= link_to @user.twitter_url, @user.twitter_url, :target=>["_blank"] %></p>
    </div>

    <% if logged_in? && @user == current_user %>
      <div class='tweet-btn'>
        <div class='tweet-label'>今日の作業時間をツイートする</div>
        <a href="https://twitter.com/share?ref_src=twsrc%5Etfw"
        data-text='<%= "今日の作業時間は#{@working_today_hour}時間#{@working_today_minute}分でした。" %>'
        class="twitter-share-button" data-show-count="false">tweet</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
      <div class='clear'></div>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='col-md-10 col-md-offset-1'>

    <%= will_paginate @posts %>

    <div id='user-posts-mobile'>
      <%= render 'posts/posts_table_mobile' %>
    </div>

    <div id='user-posts-pc'>
      <%= render 'posts/posts_table_pc' %>
    </div>

    <%= will_paginate @posts %>

    <% if logged_in? && @user == current_user %>
      <p id='post-btn'><%= link_to new_post_path do %>
        <i class="fas fa-edit"></i>
      <% end %>
    <% end %>
  </div>
</div>