config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'users#index'
  get 'help' => 'home#help'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  delete 'logout' => 'sessions#destroy'

  # Twitterでのログイン
  get 'auth/:provider/callback' => 'sessions#create'

  resources :users do
    # 検索処理アクション
    collection do
      get :search_form
      get :search_result
    end
    # フォロー表示ページ
    member do
      get :following
    end
  end
  resources :posts
  resources :relationships, only: [:create, :destroy]

  # テスト用ログインアクション
  if Rails.env.test?
    post 'test/login' => 'sessions#login'
  end
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <small>&copy; 2018 あかしぃ</small>
  <nav>
    <ul>
      <li><%= link_to 'ブログろぐとは？', help_path %></li>
      <li><%= link_to '運営者', 'https://twitter.com/akashi__akashi?lang=ja', :target=>['_blank'] %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to 'ブログろぐ', users_path, id: 'logo' %>
    <nav>
      <ul class='nav navbar-nav navbar-right' id='pc-nav'>
        <li><%= link_to 'トップ', users_path %></li>
        <% if logged_in? %>
          <li><%= link_to '記録する', new_post_path %></li>
          <li><%= link_to 'マイページ', user_path(current_user) %></li>
          <li><%= link_to 'フォロー一覧', following_user_path(current_user) %></li>
          <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ブログろぐとは？', help_path %></li>
          <li><%= link_to 'ログイン/新規登録', '/auth/twitter' %></li>
        <% end %>
      </ul>

      <ul class='nav navbar-nav navbar-right' id='mobile-nav'>
        <% if logged_in? %>
          <li class='mobile-gloval-nav'>
            <%= link_to 'マイページ', user_path(current_user) %>
          </li>
          <li class='dropdown mobile-gloval-nav'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
              <i class="fas fa-bars"></i><b class='caret'></b>
            </a>
            <ul class='dropdown-menu'>
              <li><%= link_to 'トップへ', root_path %></li>
              <li><%= link_to '記録する', new_post_path %></li>
              <li><%= link_to 'フォロー一覧', following_user_path(current_user) %></li>
              <li><%= link_to 'ユーザー検索', search_form_users_path %></li>
              <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'ログイン', '/auth/twitter' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <%= render 'layouts/shim' %>
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="ブログろぐ">
    <meta name="twitter:description" content="ブログろぐは毎日の作業時間を記録できるサービスです">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='flash'>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>
    <div class='container'>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>